// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bktscqhsggcbpnyjzytm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdHNjcWhzZ2djYnBueWp6eXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwODU2OTQsImV4cCI6MjA3NjY2MTY5NH0.D3Q0QGSX-7PtwGyQQi27Mmojz0R1W5hGm24U-XP-6Mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});